# Generated by Django 5.2.6 on 2025-12-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_store', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_ad',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
