# Generated by Django 5.2.6 on 2025-12-26 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_store', '0008_alter_order_create_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_ad',
            new_name='create_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='номер не вказано', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')]),
        ),
    ]
