# Generated by Django 5.2.6 on 2025-12-26 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_store', '0010_order_user_ordercart_order_order_cart_ordercartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercartitem',
            name='price_at_purchase',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_online_store.ordercart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
