# Generated by Django 5.2.6 on 2025-12-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_store', '0011_remove_ordercartitem_price_at_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercartitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
